#include <gtest/gtest.h>

#include "generator/csharp/TkPacketCSharpGenerator.h"

#include <pstk/TkResult.h>

#include <cstddef>
#include <filesystem>
#include <string>

namespace
{
pstk::packet::PacketDescriptor MakeAllTypesDescriptor()
{
    return {
        "AllTypes.packet.json",
        "AllTypes",
        4660,
        1,
        0,
        2,
        32,
        {
            {"int8Value", pstk::packet::PacketPrimitiveType::Int8, 2, 1},
            {"uint8Value", pstk::packet::PacketPrimitiveType::UInt8, 3, 1},
            {"int16Value", pstk::packet::PacketPrimitiveType::Int16, 4, 2},
            {"uint16Value", pstk::packet::PacketPrimitiveType::UInt16, 6, 2},
            {"int32Value", pstk::packet::PacketPrimitiveType::Int32, 8, 4},
            {"uint32Value", pstk::packet::PacketPrimitiveType::UInt32, 12, 4},
            {"int64Value", pstk::packet::PacketPrimitiveType::Int64, 16, 8},
            {"uint64Value", pstk::packet::PacketPrimitiveType::UInt64, 24, 8},
        },
    };
}
} // namespace

TEST(TkPacketCSharpGenerator, PreservesSchemaNamesAndGeneratesCodec)
{
    const pstk::packet::PacketDescriptor descriptor = MakeAllTypesDescriptor();
    const pstk::packet::CSharpPacketCodeGenerator generator("Pstk.Generated");
    pstk::packet::GeneratedFile generatedFile;
    pstk::packet::GeneratedFile repeatedFile;

    ASSERT_EQ(generator.Generate(descriptor, &generatedFile), TK_SUCCESS);
    ASSERT_EQ(generator.Generate(descriptor, &repeatedFile), TK_SUCCESS);
    EXPECT_EQ(generatedFile.fileName, std::filesystem::path("AllTypes.generated.cs"));
    EXPECT_EQ(generatedFile.contents, repeatedFile.contents);
    EXPECT_EQ(generatedFile.contents.find('\r'), std::string::npos);
    EXPECT_EQ(generatedFile.contents.rfind("// Generated by PrivateServerToolKit. Do not edit.\n", 0), 0U);

    EXPECT_NE(generatedFile.contents.find("namespace Pstk.Generated"), std::string::npos);
    EXPECT_NE(generatedFile.contents.find("public readonly record struct AllTypes("), std::string::npos);
    EXPECT_NE(generatedFile.contents.find("sbyte int8Value"), std::string::npos);
    EXPECT_NE(generatedFile.contents.find("byte uint8Value"), std::string::npos);
    EXPECT_NE(generatedFile.contents.find("short int16Value"), std::string::npos);
    EXPECT_NE(generatedFile.contents.find("ushort uint16Value"), std::string::npos);
    EXPECT_NE(generatedFile.contents.find("int int32Value"), std::string::npos);
    EXPECT_NE(generatedFile.contents.find("uint uint32Value"), std::string::npos);
    EXPECT_NE(generatedFile.contents.find("long int64Value"), std::string::npos);
    EXPECT_NE(generatedFile.contents.find("ulong uint64Value"), std::string::npos);
    EXPECT_EQ(generatedFile.contents.find("Int8Value"), std::string::npos);
    EXPECT_NE(generatedFile.contents.find("public const ushort PacketId = 4660;"), std::string::npos);
    EXPECT_NE(generatedFile.contents.find("public const ushort PayloadVersion = 1;"), std::string::npos);
    EXPECT_NE(generatedFile.contents.find("public const int PayloadBytes = 32;"), std::string::npos);
    EXPECT_NE(generatedFile.contents.find("TryEncode(AllTypes value, Span<byte> output)"), std::string::npos);
    EXPECT_NE(generatedFile.contents.find("TryDecode(ReadOnlySpan<byte> input, out AllTypes value)"),
              std::string::npos);
    EXPECT_NE(
        generatedFile.contents.find(
            "WriteInt16LittleEndian(\n                output,\n                4,\n                value.int16Value)"),
        std::string::npos);
    EXPECT_NE(generatedFile.contents.find("ReadUInt64LittleEndian(input, 24)"), std::string::npos);
}

TEST(TkPacketCSharpGenerator, GeneratesEmptyPacket)
{
    const pstk::packet::PacketDescriptor descriptor = {
        "Empty.packet.json", "Empty", 1, 1, 0, 2, 2, {},
    };
    std::string source;

    ASSERT_EQ(pstk::packet::GenerateCSharpSource(descriptor, "Pstk.Generated", &source), TK_SUCCESS);
    EXPECT_NE(source.find("public readonly record struct Empty"), std::string::npos);
    EXPECT_NE(source.find("public const int PayloadBytes = 2;"), std::string::npos);
    EXPECT_NE(source.find("Empty decoded = new Empty();"), std::string::npos);
}
