#include "generator/cpp/TkPacketCppGenerator.h"
#include "generator/csharp/TkPacketCSharpGenerator.h"

#include <pstk/TkResult.h>

#include <cstddef>
#include <cstdint>
#include <fstream>
#include <string>

namespace
{
bool WriteFile(const char *const outputPath, const std::string &contents)
{
    if (outputPath == nullptr)
    {
        return false;
    }

    std::ofstream output(outputPath, std::ios::binary);
    if (!output)
    {
        return false;
    }

    output.write(contents.data(), static_cast<std::streamsize>(contents.size()));
    return static_cast<bool>(output);
}
} // namespace

int main(const int argumentCount, const char *const *const arguments)
{
    // arguments: path for genarated packet
    // cpp header
    // csharp shoource
    if (argumentCount != 3)
    {
        return 1;
    }

    pstk::packet::PacketDescriptor descriptor = {
        "AllTypes.packet.json",
        "AllTypes",
        4660,
        1,
        0,
        2,
        32,
        {
            {"int8Value", pstk::packet::PacketPrimitiveType::Int8, 2, 1},
            {"uint8Value", pstk::packet::PacketPrimitiveType::UInt8, 3, 1},
            {"int16Value", pstk::packet::PacketPrimitiveType::Int16, 4, 2},
            {"uint16Value", pstk::packet::PacketPrimitiveType::UInt16, 6, 2},
            {"int32Value", pstk::packet::PacketPrimitiveType::Int32, 8, 4},
            {"uint32Value", pstk::packet::PacketPrimitiveType::UInt32, 12, 4},
            {"int64Value", pstk::packet::PacketPrimitiveType::Int64, 16, 8},
            {"uint64Value", pstk::packet::PacketPrimitiveType::UInt64, 24, 8},
        },
    };

    std::string generatedHeader;
    if (pstk::packet::GenerateCppHeader(descriptor, "pstk::packet::generated_test", &generatedHeader) != TK_SUCCESS)
    {
        return 1;
    }

    std::string repeatedHeader;
    if (pstk::packet::GenerateCppHeader(descriptor, "pstk::packet::generated_test", &repeatedHeader) != TK_SUCCESS ||
        repeatedHeader != generatedHeader || generatedHeader.find('\r') != std::string::npos ||
        generatedHeader.rfind("// Generated by PrivateServerToolKit. Do not edit.\n", 0) != 0)
    {
        return 1;
    }

    std::string generatedSource;
    if (pstk::packet::GenerateCSharpSource(descriptor, "Pstk.Generated", &generatedSource) != TK_SUCCESS)
    {
        return 1;
    }

    if (!WriteFile(arguments[1], generatedHeader))
    {
        return 1;
    }

    return WriteFile(arguments[2], generatedSource) ? 0 : 1;
}
