#include "TkPacketCppGenerator.h"

#include <cstddef>
#include <string>
#include <utility>

namespace pstk::packet
{
namespace
{
const char *GetCppTypeName(const PacketPrimitiveType type)
{
    switch (type)
    {
    case PacketPrimitiveType::Int8:
        return "std::int8_t";
    case PacketPrimitiveType::UInt8:
        return "std::uint8_t";
    case PacketPrimitiveType::Int16:
        return "std::int16_t";
    case PacketPrimitiveType::UInt16:
        return "std::uint16_t";
    case PacketPrimitiveType::Int32:
        return "std::int32_t";
    case PacketPrimitiveType::UInt32:
        return "std::uint32_t";
    case PacketPrimitiveType::Int64:
        return "std::int64_t";
    case PacketPrimitiveType::UInt64:
        return "std::uint64_t";
    }

    return nullptr;
}

bool FitsPayload(const std::size_t offset, const std::size_t size, const std::size_t payloadBytes)
{
    return size > 0 && offset <= payloadBytes && size <= payloadBytes - offset;
}

bool HasValidDescriptorBounds(const PacketDescriptor &descriptor)
{
    if (!FitsPayload(descriptor.payloadVersionOffset, descriptor.payloadVersionSize, descriptor.payloadBytes))
    {
        return false;
    }

    for (const FieldDescriptor &field : descriptor.fields)
    {
        if (!FitsPayload(field.offset, field.size, descriptor.payloadBytes))
        {
            return false;
        }
    }

    return true;
}

void AppendLine(std::string *const output, const std::string &line = {})
{
    output->append(line);
    output->push_back('\n');
}

void AppendEncodeField(std::string *const output, const char *const typeName, const std::string &valueExpression,
                       const std::size_t offset)
{
    AppendLine(output, "        pstk::packet::detail::WriteLittleEndian<" + std::string(typeName) + ">(");
    AppendLine(output, "            " + valueExpression + ", encoded.data() + " + std::to_string(offset) + ");");
}

void AppendDecodeField(std::string *const output, const FieldDescriptor &field, const char *const typeName)
{
    AppendLine(output, "        decoded." + field.name + " = pstk::packet::detail::ReadLittleEndian<" +
                           std::string(typeName) + ">(input.data + " + std::to_string(field.offset) + ");");
}
} // namespace

TkResult GenerateCppHeader(const PacketDescriptor &descriptor, const char *const namespaceName,
                           std::string *const outHeader)
{
    if (namespaceName == nullptr || namespaceName[0] == '\0' || outHeader == nullptr)
    {
        return TK_ERROR_INVALID_ARGUMENT;
    }

    if (descriptor.name.empty() || !HasValidDescriptorBounds(descriptor))
    {
        return TK_ERROR_INVALID_DATA;
    }

    std::string header;
    AppendLine(&header, "// Generated by PrivateServerToolKit. Do not edit.");
    AppendLine(&header, "#pragma once");
    AppendLine(&header);
    AppendLine(&header, "#include <pstk/packet/TkPacketCodecSupport.h>");
    AppendLine(&header);
    AppendLine(&header, "#include <algorithm>");
    AppendLine(&header, "#include <array>");
    AppendLine(&header, "#include <cstddef>");
    AppendLine(&header, "#include <cstdint>");
    AppendLine(&header);
    AppendLine(&header, "namespace " + std::string(namespaceName));
    AppendLine(&header, "{");
    AppendLine(&header, "struct " + descriptor.name);
    AppendLine(&header, "{");
    AppendLine(&header, "    static constexpr std::uint16_t PacketId = " + std::to_string(descriptor.id) + ";");
    AppendLine(&header, "    static constexpr std::uint16_t PayloadVersion = " +
                            std::to_string(descriptor.payloadVersion) + ";");
    AppendLine(&header,
               "    static constexpr std::size_t PayloadBytes = " + std::to_string(descriptor.payloadBytes) + ";");

    if (!descriptor.fields.empty())
    {
        AppendLine(&header);
    }

    for (const FieldDescriptor &field : descriptor.fields)
    {
        const char *const typeName = GetCppTypeName(field.type);
        if (typeName == nullptr)
        {
            return TK_ERROR_INVALID_DATA;
        }

        AppendLine(&header, "    " + std::string(typeName) + " " + field.name + "{};");
    }

    AppendLine(&header);
    AppendLine(&header, "    TkResult Encode(TkMutableByteView output,");
    AppendLine(&header, "                    TkDiagnosticCallbackInfo diagnosticCallback = {}) const");
    AppendLine(&header, "    {");
    AppendLine(&header, "        const TkResult validationResult =");
    AppendLine(&header,
               "            pstk::packet::detail::ValidateEncodeView(output, PayloadBytes, diagnosticCallback);");
    AppendLine(&header, "        if (validationResult != TK_SUCCESS)");
    AppendLine(&header, "        {");
    AppendLine(&header, "            return validationResult;");
    AppendLine(&header, "        }");
    AppendLine(&header);
    AppendLine(&header, "        std::array<std::uint8_t, PayloadBytes> encoded{};");
    AppendEncodeField(&header, "std::uint16_t", "PayloadVersion", descriptor.payloadVersionOffset);
    for (const FieldDescriptor &field : descriptor.fields)
    {
        const char *const typeName = GetCppTypeName(field.type);
        AppendEncodeField(&header, typeName, field.name, field.offset);
    }
    AppendLine(&header, "        std::copy(encoded.begin(), encoded.end(), output.data);");
    AppendLine(&header, "        return TK_SUCCESS;");
    AppendLine(&header, "    }");
    AppendLine(&header);
    AppendLine(&header, "    TkResult Decode(TkByteView input, TkDiagnosticCallbackInfo diagnosticCallback = {})");
    AppendLine(&header, "    {");
    AppendLine(&header, "        const TkResult validationResult =");
    AppendLine(&header,
               "            pstk::packet::detail::ValidateDecodeView(input, PayloadBytes, diagnosticCallback);");
    AppendLine(&header, "        if (validationResult != TK_SUCCESS)");
    AppendLine(&header, "        {");
    AppendLine(&header, "            return validationResult;");
    AppendLine(&header, "        }");
    AppendLine(&header);
    AppendLine(&header, "        const std::uint16_t payloadVersion =");
    AppendLine(&header, "            pstk::packet::detail::ReadLittleEndian<std::uint16_t>(input.data + " +
                            std::to_string(descriptor.payloadVersionOffset) + ");");
    AppendLine(&header, "        const TkResult versionResult = pstk::packet::detail::ValidatePayloadVersion(");
    AppendLine(&header, "            payloadVersion, PayloadVersion, diagnosticCallback);");
    AppendLine(&header, "        if (versionResult != TK_SUCCESS)");
    AppendLine(&header, "        {");
    AppendLine(&header, "            return versionResult;");
    AppendLine(&header, "        }");
    AppendLine(&header);
    AppendLine(&header, "        " + descriptor.name + " decoded{};");
    for (const FieldDescriptor &field : descriptor.fields)
    {
        const char *const typeName = GetCppTypeName(field.type);
        AppendDecodeField(&header, field, typeName);
    }
    AppendLine(&header, "        *this = decoded;");
    AppendLine(&header, "        return TK_SUCCESS;");
    AppendLine(&header, "    }");
    AppendLine(&header, "};");
    AppendLine(&header, "} // namespace " + std::string(namespaceName));

    *outHeader = std::move(header);
    return TK_SUCCESS;
}
} // namespace pstk::packet
