#include "TkPacketCSharpGenerator.h"

#include <cstddef>
#include <filesystem>
#include <string>
#include <utility>

namespace pstk::packet
{
namespace
{
const char *GetCSharpTypeName(const PacketPrimitiveType type)
{
    switch (type)
    {
    case PacketPrimitiveType::Int8:
        return "sbyte";
    case PacketPrimitiveType::UInt8:
        return "byte";
    case PacketPrimitiveType::Int16:
        return "short";
    case PacketPrimitiveType::UInt16:
        return "ushort";
    case PacketPrimitiveType::Int32:
        return "int";
    case PacketPrimitiveType::UInt32:
        return "uint";
    case PacketPrimitiveType::Int64:
        return "long";
    case PacketPrimitiveType::UInt64:
        return "ulong";
    }

    return nullptr;
}

const char *GetCSharpWriteMethodName(const PacketPrimitiveType type)
{
    switch (type)
    {
    case PacketPrimitiveType::Int8:
        return "WriteInt8";
    case PacketPrimitiveType::UInt8:
        return "WriteUInt8";
    case PacketPrimitiveType::Int16:
        return "WriteInt16LittleEndian";
    case PacketPrimitiveType::UInt16:
        return "WriteUInt16LittleEndian";
    case PacketPrimitiveType::Int32:
        return "WriteInt32LittleEndian";
    case PacketPrimitiveType::UInt32:
        return "WriteUInt32LittleEndian";
    case PacketPrimitiveType::Int64:
        return "WriteInt64LittleEndian";
    case PacketPrimitiveType::UInt64:
        return "WriteUInt64LittleEndian";
    }

    return nullptr;
}

const char *GetCSharpReadMethodName(const PacketPrimitiveType type)
{
    switch (type)
    {
    case PacketPrimitiveType::Int8:
        return "ReadInt8";
    case PacketPrimitiveType::UInt8:
        return "ReadUInt8";
    case PacketPrimitiveType::Int16:
        return "ReadInt16LittleEndian";
    case PacketPrimitiveType::UInt16:
        return "ReadUInt16LittleEndian";
    case PacketPrimitiveType::Int32:
        return "ReadInt32LittleEndian";
    case PacketPrimitiveType::UInt32:
        return "ReadUInt32LittleEndian";
    case PacketPrimitiveType::Int64:
        return "ReadInt64LittleEndian";
    case PacketPrimitiveType::UInt64:
        return "ReadUInt64LittleEndian";
    }

    return nullptr;
}

bool FitsPayload(const std::size_t offset, const std::size_t size, const std::size_t payloadBytes)
{
    return size > 0 && offset <= payloadBytes && size <= payloadBytes - offset;
}

bool HasValidDescriptorBounds(const PacketDescriptor &descriptor)
{
    if (!FitsPayload(descriptor.payloadVersionOffset, descriptor.payloadVersionSize, descriptor.payloadBytes))
    {
        return false;
    }

    for (const FieldDescriptor &field : descriptor.fields)
    {
        if (!FitsPayload(field.offset, field.size, descriptor.payloadBytes))
        {
            return false;
        }
    }

    return true;
}

void AppendLine(std::string *const output, const std::string &line = {})
{
    output->append(line);
    output->push_back('\n');
}

void AppendWriteCall(std::string *const output, const char *const methodName, const std::string &valueExpression,
                     const std::size_t offset)
{
    AppendLine(output, "            global::Pstk.Packet.TkPacketCodecSupport." + std::string(methodName) + "(");
    AppendLine(output, "                output,");
    AppendLine(output, "                " + std::to_string(offset) + ",");
    AppendLine(output, "                " + valueExpression + ");");
}

std::string BuildReadExpression(const char *const methodName, const std::size_t offset)
{
    return "global::Pstk.Packet.TkPacketCodecSupport." + std::string(methodName) + "(input, " + std::to_string(offset) +
           ")";
}
} // namespace

TkResult GenerateCSharpSource(const PacketDescriptor &descriptor, const char *const namespaceName,
                              std::string *const outSource)
{
    if (outSource == nullptr)
    {
        return TK_ERROR_INVALID_ARGUMENT;
    }

    const bool hasNamespace = namespaceName != nullptr && namespaceName[0] != '\0';

    if (descriptor.name.empty() || !HasValidDescriptorBounds(descriptor))
    {
        return TK_ERROR_INVALID_DATA;
    }

    std::string source;
    AppendLine(&source, "// Generated by PrivateServerToolKit. Do not edit.");
    AppendLine(&source, "using System;");
    AppendLine(&source);
    if (hasNamespace)
    {
        AppendLine(&source, "namespace " + std::string(namespaceName));
        AppendLine(&source, "{");
    }

    if (descriptor.fields.empty())
    {
        AppendLine(&source, "    public readonly record struct " + descriptor.name + "()");
    }
    else
    {
        AppendLine(&source, "    public readonly record struct " + descriptor.name + "(");
        for (std::size_t fieldIndex = 0; fieldIndex < descriptor.fields.size(); ++fieldIndex)
        {
            const FieldDescriptor &field = descriptor.fields[fieldIndex];
            const char *const typeName = GetCSharpTypeName(field.type);
            if (typeName == nullptr)
            {
                return TK_ERROR_INVALID_DATA;
            }

            const char *const suffix = fieldIndex + 1 < descriptor.fields.size() ? "," : ")";
            AppendLine(&source, "        " + std::string(typeName) + " " + field.name + suffix);
        }
    }

    AppendLine(&source, "    {");
    AppendLine(&source, "        public const ushort PacketId = " + std::to_string(descriptor.id) + ";");
    AppendLine(&source,
               "        public const ushort PayloadVersion = " + std::to_string(descriptor.payloadVersion) + ";");
    AppendLine(&source, "        public const int PayloadBytes = " + std::to_string(descriptor.payloadBytes) + ";");
    AppendLine(&source);
    AppendLine(&source, "        public static bool TryEncode(" + descriptor.name + " value, Span<byte> output)");
    AppendLine(&source, "        {");
    AppendLine(&source, "            if (output.Length != PayloadBytes)");
    AppendLine(&source, "            {");
    AppendLine(&source, "                return false;");
    AppendLine(&source, "            }");
    AppendLine(&source);
    AppendWriteCall(&source, "WriteUInt16LittleEndian", "PayloadVersion", descriptor.payloadVersionOffset);
    for (const FieldDescriptor &field : descriptor.fields)
    {
        const char *const methodName = GetCSharpWriteMethodName(field.type);
        if (methodName == nullptr)
        {
            return TK_ERROR_INVALID_DATA;
        }

        AppendWriteCall(&source, methodName, "value." + field.name, field.offset);
    }
    AppendLine(&source, "            return true;");
    AppendLine(&source, "        }");
    AppendLine(&source);
    AppendLine(&source,
               "        public static bool TryDecode(ReadOnlySpan<byte> input, out " + descriptor.name + " value)");
    AppendLine(&source, "        {");
    AppendLine(&source, "            value = default;");
    AppendLine(&source, "            if (input.Length != PayloadBytes)");
    AppendLine(&source, "            {");
    AppendLine(&source, "                return false;");
    AppendLine(&source, "            }");
    AppendLine(&source);
    AppendLine(&source, "            if (" +
                            BuildReadExpression("ReadUInt16LittleEndian", descriptor.payloadVersionOffset) +
                            " != PayloadVersion)");
    AppendLine(&source, "            {");
    AppendLine(&source, "                return false;");
    AppendLine(&source, "            }");
    AppendLine(&source);

    if (descriptor.fields.empty())
    {
        AppendLine(&source, "            " + descriptor.name + " decoded = new " + descriptor.name + "();");
    }
    else
    {
        AppendLine(&source, "            " + descriptor.name + " decoded = new " + descriptor.name + "(");
        for (std::size_t fieldIndex = 0; fieldIndex < descriptor.fields.size(); ++fieldIndex)
        {
            const FieldDescriptor &field = descriptor.fields[fieldIndex];
            const char *const methodName = GetCSharpReadMethodName(field.type);
            if (methodName == nullptr)
            {
                return TK_ERROR_INVALID_DATA;
            }

            const char *const suffix = fieldIndex + 1 < descriptor.fields.size() ? "," : ");";
            AppendLine(&source, "                " + BuildReadExpression(methodName, field.offset) + suffix);
        }
    }
    AppendLine(&source, "            value = decoded;");
    AppendLine(&source, "            return true;");
    AppendLine(&source, "        }");
    AppendLine(&source, "    }");
    if (hasNamespace)
    {
        AppendLine(&source, "}");
    }

    *outSource = std::move(source);
    return TK_SUCCESS;
}

CSharpPacketCodeGenerator::CSharpPacketCodeGenerator(const char *const namespaceName)
    : namespaceName_(namespaceName != nullptr ? namespaceName : "")
{
}

TkResult CSharpPacketCodeGenerator::Generate(const PacketDescriptor &descriptor, GeneratedFile *const outFile) const
{
    if (outFile == nullptr)
    {
        return TK_ERROR_INVALID_ARGUMENT;
    }

    GeneratedFile generatedFile;
    const TkResult result = GenerateCSharpSource(descriptor, namespaceName_.c_str(), &generatedFile.contents);
    if (result != TK_SUCCESS)
    {
        return result;
    }

    generatedFile.fileName = std::filesystem::u8path(descriptor.name + ".generated.cs");
    *outFile = std::move(generatedFile);
    return TK_SUCCESS;
}
} // namespace pstk::packet
