#version 450

layout(local_size_x = 16, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) buffer DataBuffer {
    uint values[];
} dataBuffer;

void main() {
    uint bufferLength = dataBuffer.values.length(); //length는 descriptor range와 shader에 선언한 배열의 원소 간격을 기준으로 원소 개수 계산
    uint index = gl_GlobalInvocationID.x;

    if (index >= bufferLength) {
        return;
    }

    dataBuffer.values[index] *= 2u;
}
