#version 450

layout(local_size_x = 16, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) buffer DataBuffer {
    uint values[];
} dataBuffer;

// push_constant로 전달된 값을 이 형식으로 읽겠다고 선언
// uniform : push constant 블록 선언에 사용하는 문법
layout(push_constant, std430) uniform ComputeParameters
{
    uint elementCount;
    uint multiplier;
} parameters;

void main() {
    uint index = gl_GlobalInvocationID.x;

    if (index >= parameters.elementCount
            || index >= uint(dataBuffer.values.length())) {
        return;
    }

    dataBuffer.values[index] *= parameters.multiplier;
}
