<Project>
  <!-- See https://aka.ms/dotnet/msbuild/customize for more details on customizing your build -->

  <!-- $(Configuration): dotnet build -c {Debug/Release} -->
  <!-- $(MSBuildThisFileDirectory): props 파일 위치 -->

  <PropertyGroup Condition="'$(Configuration)' == 'Debug' and '$(PstkGeneratedSourceDir)' == ''">
    <PstkGeneratedSourceDir>$(MSBuildThisFileDirectory)../../out/build/dev/tools/packet/tests/generated</PstkGeneratedSourceDir>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release' and '$(PstkGeneratedSourceDir)' == ''">
    <PstkGeneratedSourceDir>$(MSBuildThisFileDirectory)../../out/build/release/tools/packet/tests/generated</PstkGeneratedSourceDir>
  </PropertyGroup>
</Project>
